// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet.proto

package greetpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Greeting is a greeting.
type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

// GreetRequest is a request payload for the Greet RPC.
type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// GreetResponse is a response from the Greet RPC.
type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{2}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// GreetManyRequest is a request payload for the GreetMany RPC.
type GreetManyRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetManyRequest) Reset()         { *m = GreetManyRequest{} }
func (m *GreetManyRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyRequest) ProtoMessage()    {}
func (*GreetManyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{3}
}

func (m *GreetManyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyRequest.Unmarshal(m, b)
}
func (m *GreetManyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyRequest.Marshal(b, m, deterministic)
}
func (m *GreetManyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyRequest.Merge(m, src)
}
func (m *GreetManyRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyRequest.Size(m)
}
func (m *GreetManyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyRequest proto.InternalMessageInfo

func (m *GreetManyRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// GreetManyResponse is a response from the GreetMany RPC.
type GreetManyResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyResponse) Reset()         { *m = GreetManyResponse{} }
func (m *GreetManyResponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyResponse) ProtoMessage()    {}
func (*GreetManyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{4}
}

func (m *GreetManyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyResponse.Unmarshal(m, b)
}
func (m *GreetManyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyResponse.Marshal(b, m, deterministic)
}
func (m *GreetManyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyResponse.Merge(m, src)
}
func (m *GreetManyResponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyResponse.Size(m)
}
func (m *GreetManyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyResponse proto.InternalMessageInfo

func (m *GreetManyResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// LongGreetRequest is a request payload for the LongGreet RPC.
type LongGreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LongGreetRequest) Reset()         { *m = LongGreetRequest{} }
func (m *LongGreetRequest) String() string { return proto.CompactTextString(m) }
func (*LongGreetRequest) ProtoMessage()    {}
func (*LongGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{5}
}

func (m *LongGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetRequest.Unmarshal(m, b)
}
func (m *LongGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetRequest.Marshal(b, m, deterministic)
}
func (m *LongGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetRequest.Merge(m, src)
}
func (m *LongGreetRequest) XXX_Size() int {
	return xxx_messageInfo_LongGreetRequest.Size(m)
}
func (m *LongGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetRequest proto.InternalMessageInfo

func (m *LongGreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// LongGreetResponse is a response from the LongGreet RPC.
type LongGreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetResponse) Reset()         { *m = LongGreetResponse{} }
func (m *LongGreetResponse) String() string { return proto.CompactTextString(m) }
func (*LongGreetResponse) ProtoMessage()    {}
func (*LongGreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{6}
}

func (m *LongGreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetResponse.Unmarshal(m, b)
}
func (m *LongGreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetResponse.Marshal(b, m, deterministic)
}
func (m *LongGreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetResponse.Merge(m, src)
}
func (m *LongGreetResponse) XXX_Size() int {
	return xxx_messageInfo_LongGreetResponse.Size(m)
}
func (m *LongGreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetResponse proto.InternalMessageInfo

func (m *LongGreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// GreetEveryoneRequest is a request payload for the GreetEveryone RPC.
type GreetEveryoneRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetEveryoneRequest) Reset()         { *m = GreetEveryoneRequest{} }
func (m *GreetEveryoneRequest) String() string { return proto.CompactTextString(m) }
func (*GreetEveryoneRequest) ProtoMessage()    {}
func (*GreetEveryoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{7}
}

func (m *GreetEveryoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryoneRequest.Unmarshal(m, b)
}
func (m *GreetEveryoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryoneRequest.Marshal(b, m, deterministic)
}
func (m *GreetEveryoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryoneRequest.Merge(m, src)
}
func (m *GreetEveryoneRequest) XXX_Size() int {
	return xxx_messageInfo_GreetEveryoneRequest.Size(m)
}
func (m *GreetEveryoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryoneRequest proto.InternalMessageInfo

func (m *GreetEveryoneRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// GreetEveryoneResponse is a response from the GreetEveryone RPC.
type GreetEveryoneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryoneResponse) Reset()         { *m = GreetEveryoneResponse{} }
func (m *GreetEveryoneResponse) String() string { return proto.CompactTextString(m) }
func (*GreetEveryoneResponse) ProtoMessage()    {}
func (*GreetEveryoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{8}
}

func (m *GreetEveryoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryoneResponse.Unmarshal(m, b)
}
func (m *GreetEveryoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryoneResponse.Marshal(b, m, deterministic)
}
func (m *GreetEveryoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryoneResponse.Merge(m, src)
}
func (m *GreetEveryoneResponse) XXX_Size() int {
	return xxx_messageInfo_GreetEveryoneResponse.Size(m)
}
func (m *GreetEveryoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryoneResponse proto.InternalMessageInfo

func (m *GreetEveryoneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
	proto.RegisterType((*GreetManyRequest)(nil), "greet.GreetManyRequest")
	proto.RegisterType((*GreetManyResponse)(nil), "greet.GreetManyResponse")
	proto.RegisterType((*LongGreetRequest)(nil), "greet.LongGreetRequest")
	proto.RegisterType((*LongGreetResponse)(nil), "greet.LongGreetResponse")
	proto.RegisterType((*GreetEveryoneRequest)(nil), "greet.GreetEveryoneRequest")
	proto.RegisterType((*GreetEveryoneResponse)(nil), "greet.GreetEveryoneResponse")
}

func init() {
	proto.RegisterFile("greet.proto", fileDescriptor_32c0044392f32579)
}

var fileDescriptor_32c0044392f32579 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x4f, 0xfa, 0x30,
	0x14, 0xc0, 0x19, 0x09, 0x84, 0x3d, 0xbe, 0xdf, 0x28, 0x15, 0x95, 0x80, 0x26, 0x66, 0x17, 0x49,
	0x48, 0x28, 0xa0, 0x37, 0x0f, 0x26, 0x18, 0xf5, 0xa2, 0xc6, 0xe0, 0xcd, 0x0b, 0x19, 0xf0, 0x9c,
	0x4b, 0x58, 0x3b, 0xdb, 0x42, 0xc2, 0x3f, 0xe3, 0xdf, 0x6a, 0x56, 0xba, 0x59, 0xc1, 0x48, 0xb2,
	0xdb, 0xde, 0x8f, 0x7d, 0x3e, 0xed, 0x7b, 0x1b, 0x54, 0x03, 0x81, 0xa8, 0xba, 0xb1, 0xe0, 0x8a,
	0x93, 0x92, 0x0e, 0xbc, 0x3b, 0xa8, 0xdc, 0x27, 0x0f, 0x21, 0x0b, 0xc8, 0x29, 0xc0, 0x5b, 0x28,
	0xa4, 0x1a, 0x33, 0x3f, 0xc2, 0x86, 0x73, 0xe6, 0xb4, 0xdd, 0x91, 0xab, 0x33, 0x4f, 0x7e, 0x84,
	0xa4, 0x05, 0xee, 0xdc, 0x4f, 0xab, 0x45, 0x5d, 0xad, 0x24, 0x89, 0xa4, 0xe8, 0x5d, 0xc1, 0x3f,
	0xcd, 0x19, 0xe1, 0xc7, 0x02, 0xa5, 0x22, 0x1d, 0xa8, 0x04, 0x86, 0xab, 0x49, 0xd5, 0xc1, 0x5e,
	0x77, 0xad, 0x4f, 0x75, 0xa3, 0xac, 0xc1, 0x3b, 0x87, 0xff, 0xe6, 0x65, 0x19, 0x73, 0x26, 0x91,
	0x1c, 0x41, 0x59, 0xa0, 0x5c, 0xcc, 0x95, 0x39, 0x85, 0x89, 0xbc, 0x6b, 0xd8, 0xd7, 0x8d, 0x8f,
	0x3e, 0x5b, 0xe5, 0x32, 0x75, 0xa0, 0x66, 0x01, 0x76, 0xdb, 0x1e, 0x38, 0x0b, 0xf2, 0xdf, 0xab,
	0x03, 0x35, 0x0b, 0xb0, 0xc3, 0x76, 0x03, 0x75, 0xdd, 0x78, 0xbb, 0x44, 0xb1, 0xe2, 0x0c, 0x73,
	0x19, 0x29, 0x1c, 0x6e, 0x40, 0xfe, 0xb6, 0x0e, 0x3e, 0x8b, 0x66, 0x71, 0x2f, 0x28, 0x96, 0xe1,
	0x14, 0xc9, 0x25, 0x94, 0x74, 0x4c, 0x0e, 0x6c, 0x8b, 0x39, 0x4c, 0xb3, 0xfe, 0x33, 0xb9, 0x86,
	0x7b, 0x05, 0x32, 0x04, 0x37, 0x9b, 0x2b, 0x39, 0xb6, 0x9b, 0xac, 0x55, 0x35, 0x1b, 0xdb, 0x85,
	0x94, 0xd0, 0x73, 0x12, 0x46, 0x36, 0xad, 0x8c, 0xb1, 0xb9, 0x80, 0x8c, 0xb1, 0x35, 0x58, 0xaf,
	0xd0, 0x76, 0xc8, 0xb3, 0xf9, 0x92, 0xd2, 0xfb, 0x93, 0x96, 0xad, 0xdc, 0x18, 0x6d, 0xf3, 0xe4,
	0xf7, 0xe2, 0x37, 0xaf, 0xe7, 0x0c, 0xfb, 0xaf, 0x34, 0x08, 0xd5, 0xfb, 0x62, 0xd2, 0x9d, 0xf2,
	0x88, 0xce, 0xd8, 0x4a, 0xf6, 0x69, 0x20, 0xe2, 0xe9, 0x78, 0x86, 0x11, 0xa7, 0x12, 0xc5, 0x12,
	0x05, 0x8d, 0xf8, 0x0c, 0xe7, 0x54, 0xc3, 0xe2, 0xc9, 0xa4, 0xac, 0xff, 0xb0, 0x8b, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc2, 0xf0, 0x26, 0xcf, 0x70, 0x03, 0x00, 0x00,
}
